# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2019-12-30 18:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kudos',
            name='from_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kudos_from_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='kudos',
            name='to_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kudos_to_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
